trigger:
  branches:
    include:
      - master
  paths:
    include:
      - Frontend/**

pool:
  vmImage: ubuntu-latest

variables:
  working_dir: '$(System.DefaultWorkingDirectory)/Frontend'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    cd $(working_dir)
    npm install
    npm run build
  displayName: 'Build React Vite app'

- task: AzureStaticWebApp@0
  inputs:
    workingDirectory: $(working_dir)
    app_location: '.'
    app_build_command: ''
    output_location: 'dist'        # Vite outputs to 'dist' by default
    skip_api_build: true
    build_timeout_in_minutes: 15
    production_branch: 'master'
  displayName: 'Deploy frontend to Azure Static Web Apps'
